name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        xcodebuild build \
          -project PhoneCare.xcodeproj \
          -scheme PhoneCare \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -skipPackagePluginValidation \
          CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: |
        xcodebuild test \
          -project PhoneCare.xcodeproj \
          -scheme PhoneCare \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -skipPackagePluginValidation \
          CODE_SIGNING_ALLOWED=NO
